[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lol-draft-tool"
version = "0.1.0"
description = "League of Legends draft phase champion sugestion tool"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv",
    "requests",
    "psycopg[binary]",
    "psycopg_pool",
    "fastapi[standard]",
]

[project.scripts]
ldt = "backend.cli:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.fastapi]
entrypoint = "backend.main:app"